# This builds the build environment, not Clarion itself.
# We use Arch Linux so that everything is automagically up to date, and we compile dependencies so that we can support arm devices.

# The image used above is built at: https://github.com/faddat/archlinux-docker and provides a nice multiplatform Arch setup. 
FROM faddat/archlinux

COPY . /clarion

ENV WASI_SDK_PREFIX=/opt/wasi-sdk

RUN pacman -Syyu --noconfirm base-devel binaryen cmake curl git boost git openssl gmp clang ninja yarn python

# Close Wasi SDK 12 & its dependencies
RUN git clone https://github.com/WebAssembly/wasi-sdk/ --branch wasi-sdk-12 --recursive

# Compile and install wasi-sdk
RUN cd wasi-sdk && \
        make -j$(nproc) && \
        cp -r build/install/opt/wasi-sdk /opt



