name: Arch Docker Build


on: [push, pull_request]

jobs:
  arch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build
      run: docker buildx build --dockerfile .devices/Dockerfile .

